### PR TITLE
fix_empty_annotation_cronjob.spec.jobTemplate.metadata

### PR DESCRIPTION
**Pull request by vjayraghavan**

### CODE REVIEW

**Review by vinny-sabatini — COMMENTED** [review]
Code change looks good to me.
@vjayraghavan did you see if we could revert this commit in your testing - https://github.com/KohlsTechnology/ansible-role-openshift-provision/commit/0c62da6f3f7ffe1cc91df9775037befe68a9fdd2
It was supposed to fix this issue before but it turns out that was not the case

**Comment by vjayraghavan** [comment]
> Code change looks good to me.
> @vjayraghavan did you see if we could revert this commit in your testing - [0c62da6](https://github.com/KohlsTechnology/ansible-role-openshift-provision/commit/0c62da6f3f7ffe1cc91df9775037befe68a9fdd2)
> It was supposed to fix this issue before but it turns out that was not the case

 I used  that commit [0c62da6] however that did not fix this issue.

**Comment by seanmalloy** [comment]
I'm wondering if we should update `normalize_ObjectMeta_V1` and/or `set_dict_defaults` methods to handle this condition. I'm still looking through the code to see if that would make sense.

**Comment by seanmalloy** [comment]
@vjayraghavan please revert commit 0c62da6 and retest to see if not specifying a `.metadata.annotations` field and `.spec.jobTemplate.metadata` still works as expected.

Looking through the code I don't think the `set_dict_defaults` method ever has any affect. It just manipulates some temporary variables which seems like a separate bug that we will need to deal with. From what I can tell the return value form the `set_dict_defaults` method always seems to be `None`, and the return value is never used when it is called. But I'm not a Python expert.

**Comment by seanmalloy** [comment]
@vjayraghavan please do not revert commit  0c62da6.

**Comment by seanmalloy** [comment]
@vjayraghavan I think there is error check missing in either the `normalize_ObjectMeta_V1` or `set_dict_defaults` methods. In my opinion one of these methods needs to be updated to fix this bug.

**Comment by vjayraghavan** [comment]
> @vjayraghavan I think there is error check missing in either the `normalize_ObjectMeta_V1` or `set_dict_defaults` methods. In my opinion one of these methods needs to be updated to fix this bug.

Updated the method normalize_ObjectMeta_V1

**Review by seanmalloy — APPROVED** [review]

**Comment by seanmalloy** [comment]
@vinny-sabatini please review one more time, and then we can merge it.

**Review by vinny-sabatini — APPROVED** [review]

**Pull request merged**
